name: Northshore Community Center
favicon: null
layout_spectrum: 0.7924325622152537
typography_spectrum: 0.45845426456071436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07723555737175047
  lightness: 0.4880402320995927
  saturation: 0.330324379960075
  rhythmicContrast: 0.844722401117906
purpose: []
