layout_spectrum: 0.16546037019138216
typography_spectrum: 0.31368402071647566
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.012950323789408153
  lightness: 0.823204392790241
  saturation: 0.9227607406148374
  rhythmicContrast: 0.2862472701492249
name: Northshore Community Center
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/360faa05-6ab2-4925-8bfb-0d211a2614ba.png
cta: {}
analytics: {}
opengraph: {}
purpose:
  - type: external
    url: 'https://www.facebook.com/LucerneNCC/'
    label: Like us on Facebook
title: Lucerne Alpine Senior Center
navigation:
  - name: Find us on Facebook
    url: 'https://www.facebook.com/LucerneNCC/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e26c51d5-b3b4-40fe-9dfa-cf778940dd10.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e26c51d5-b3b4-40fe-9dfa-cf778940dd10.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The Heart of the North Shore
github: true
url: 'http://lucernealpineseniorcenter.org/'
