layout_spectrum: 0.16546037019138216
typography_spectrum: 0.31368402071647566
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.012950323789408153
  lightness: 0.823204392790241
  saturation: 0.9227607406148374
  rhythmicContrast: 0.2862472701492249
name: Northshore Community Center
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/360faa05-6ab2-4925-8bfb-0d211a2614ba.png
cta: {}
analytics: {}
opengraph: {}
purpose:
  - type: external
    url: 'https://www.facebook.com/LucerneNCC/'
    label: Like us on Facebook
title: Northshore Community Center
navigation:
  - name: Find us on Facebook
    url: 'https://www.facebook.com/LucerneNCC/'
    type: external
content: []
description: The Heart of the North Shore
github: true
url: 'http://ncclucerne.org/'
